### PR TITLE
Allow to set minimum character height

### LINKED ISSUE #27: Allow to set minimum character height
Sometimes a source image contains small texts that should be ignored. In these cases a user needs to set minimum allowed character height.

### PR DESCRIPTION
**Pull request by wacumov**
Fixes #27

### CODE REVIEW

**Comment by wacumov** [comment]
The failed test case `testWithCustomLanguage` is flaky. Sometimes zeros are recognising as O and the test fails. Sometimes zeros are recognised correctly and test succeeds.

**Comment by Steven0351** [comment]
Something weird is going on here; when I comment out your test implementation, `testWithCustomLanguages()` passes consistently, while with it implemented it's failing consistently when all tests are run.

**Comment by Steven0351** [comment]
Of course as soon as I write that I figured something out:
```swift
  public var minimumCharacterHeight: Int? {
    didSet {
      guard let minimumCharacterHeight = minimumCharacterHeight else {
        setTesseractVariable(.oldCharacterHeight, value: "0")
        setTesseractVariable(.minimumCharacterHeight, value: "0")
        return
      }
      setTesseractVariable(.oldCharacterHeight, value: "1")
      setTesseractVariable(.minimumCharacterHeight, value: String(minimumCharacterHeight))
    }
  }
```
It seems as if for some reason these specific variables may be persisting between deinit and init. Before I got to this point I went as far as to include a function in the Tesseract capi header file that was not previously exposed to try and clear the underlying Tesseract persistent cache. When I changed your implementation in `SwiftyTesseract.swift` and then set the minimum height to nil in your test, the tests began passing.

**Comment by wacumov** [comment]
The code snippet you wrote above makes `testWithCustomLanguages()` passes, but `testNormalAndSmallFontsImage_withMinimumCharacterHeight` obviously fails in this case.

When I was looking for solution how to exclude small characters I found [this answer](https://groups.google.com/forum/#!topic/tesseract-ocr/eVVrKz8T07w)
I do not know why `textord_old_xheight` should be set to 1, but setting `textord_min_xheight ` has no effect without `textord_old_xheight = 1`

**Comment by wacumov** [comment]
[Here](https://github.com/tesseract-ocr/tesseract/blob/f80085c0bf782b8d78a395d1034a2e6842b78428/src/textord/oldbasel.cpp#L146) is the only place where `textord_old_xheight ` can affect `testWithCustomLanguages()`. 
The fact that this value is persisting after deinit is weird. 

Probably there is a more proper solution, but I found the easiest one - 
adding this line `setTesseractVariable(.oldCharacterHeight, value: "0")` to deinit makes all tests passes.

What do you think about this solution? Does it fit or it would be better to try to find something better?

**Comment by Steven0351** [comment]
I'm completely fine with that solution for the fix. I went through the Tesseract docs last night scouring for something on trying to completely wipe out the library level cache but I didn't find anything. There is a private method implemented in capi.cpp called `TessBaseAPIClearPersistentCache(handle* Tesseract)` that looked like it should have done the trick, but even after I added it to the header file and invoked it, it didn't seem to have any affect. Might be something to look into contributing upstream possibly. I'll probably add something to the docs about the potential edge cases here, because it's pretty unfortunate to have state that's difficult to control that persists beyond the life of the `Tesseract` instance at the library level. Thanks for the contribution and figuring out a solution!

**Pull request merged**
