### PR TITLE
set PDF rendering timeout to 30s

### PR DESCRIPTION
**Pull request by JulianKahnert**
We should set a timeout for the pdf page processing.

### CODE REVIEW

**Comment by Steven0351** [comment]
I’m going to merge this with the comment that if timeouts are an issue that you’re seeing (I know you’re working with PDFs quite a bit), I’m going to probably make this a parameter that’s passed into the function in the next major version (I’m currently working on this locally, haven’t pushed any code yet)

**Comment by JulianKahnert** [comment]
@Steven0351 thanks for your quick response! 🙂 What features do you have in mind for the next major version?

I was looking for some progress delegate for the PDF processing, as it is sometimes quite slow. I found something like this, but had no time to have a deeper look 🙁 
```swift
let monitor = TessMonitorCreate()
let status = TessMonitorGetProgress(monitor)
TessMonitorDelete(monitor)
```

**Comment by Steven0351** [comment]
Right now I’m converting things over to use Result as the return types from the methods and removing the closure parameter on `performOCR(on:_:)` (it used to operate on a separate dispatch queue, but that’s no longer the case, so the closure is really unnecessary).

**Comment by Steven0351** [comment]
I’ll look into the monitor thing though, any input on how you would like the API to look would be nice.

**Pull request merged**
